### ISSUE TITLE
Suggestion: add command-line options to run specific project

### ISSUE THREAD

**Issue by hsandt** [PixelVision8/PixelVision8#104]
For now, the only way to test code change immediately is to Run a project manually once from Pixel Vision OS, then make code change, focus on the Pixel Vision window and press Ctrl+4. If you accidentally close the window, you need to redo the process.

It would be convenient to have a command-line option to start a specific project directly, or at least skip the splash screen and open the project folder on start. It could then be integrated as a build command in a code editor, so the developer can work from his/her favorite environment.

Ex:
```
$ "./Pixel Vision 8" --help
Pixel Vision 8 0.9.7
Usage: "Pixel Vision 8" [options]
Options:
  --open PROJECT: open project folder on start
  --run PROJECT: run project on start
$ "./Pixel Vision 8" --run Projects/MyProject
```

**Comment by jessefreeman** [comment]
I'd like to do this. I'm not 100% on how to do it cross-platform so I'll make sure it's something I do before the final PV8 1.0 release.

**Comment by jessefreeman** [comment]
I have added an option to pass in a list of disks separated by a space or you can use these shortcuts:

-d Disks/PixelVisionOS/
-disk Disks/APIExamples/
