### ISSUE TITLE
fullscreen mode for pixelvision os

### ISSUE THREAD

**Issue by Shadowblitz16** [PixelVision8/PixelVision8#134]
can we get a fullscreen mode for pixel vision os?
the current resolution is too hard to program in especially the way the the code editor works.

I know its not exactly emulating the retro feel but I think there should be a exception for the os at least. 

EDIT: basically this would just resize the game but not scale it up

**Comment by jessefreeman** [comment]
The code editor now uses a smaller font which should help you see more code on the screen.
