### ISSUE TITLE
Tilemap Tool eraser erases both flags and and sprites.

### ISSUE THREAD

**Issue by xMGZx** [PixelVision8/PixelVision8#305]
It seems like after erasing flags in the Tilemap Tool, saving, then reloading the tilemap, sprites in those areas also get erased:
![screenshot13](https://user-images.githubusercontent.com/40220050/83361284-a2f90d80-a355-11ea-8d0d-1df82caf8713.png)

**Comment by jessefreeman** [comment]
The tilemap tool has been replaced with a single paint tool so this is no long an issue.
