### ISSUE TITLE
(.9.8) DrawSprite/Sprites/MetaSprite and useScrollPos checks

### ISSUE THREAD

**Issue by drakewill-CRL** [PixelVision8/PixelVision8#310]
In master branch, DrawSprite takes in useScrollPos as a parameter, but doesn't use it for anything. 

DrawSprites (plural) checks useScrollPos, offsets the x and y values, then passes useScrollPos to DrawSprite(singular), which doesn't check the value.

I think the correct handling of this would be to have DrawSprite use the 2 lines from DrawSprites:
startX = x - (useScrollPos ? _scrollPos.X : 0);
startY = y - (useScrollPos ? _scrollPos.Y : 0);

and for DrawSprites(plural) to either just pass the useScrollPos flag, or to do the calculation and always pass false for the useScrollPos flag, so that DrawSprite (singular) and DrawSprites (plural) would both draw the same values to the same position every time.

DrawMetaSprite passes useScrollPos to DrawSprite without calcuations, so this would also affect that function.

**Comment by drakewill-CRL** [comment]
I might not have looked close enough to fully understand this. Please correct me if I messed up the initial read of how thing should work. DrawSprite might be drawing directly to the screen coords, and DrawSprites with UseScrollPos might be drawing tiles offscreen?

**Comment by jessefreeman** [comment]
This has been removed from the new API.
