### ISSUE TITLE
Unable to open the software

### ISSUE THREAD

**Issue by MaJeeDooo0010** [PixelVision8/PixelVision8#364]
I've downloaded the installer, and did everything it says, but when it was installed and I tried opening it, it won't open. Before that, I tried installing the .zip folder, still nothing...

**Comment by jessefreeman** [comment]
What OS are you using?

**Comment by MaJeeDooo0010** [comment]
Windows 10

**Comment by jessefreeman** [comment]
A few people have had this issue but it should be fixed in the next release. I'll keep this open until I can confirm it since I've not been able to reproduce it.

**Comment by jessefreeman** [comment]
I've moved everything over to the new NetCore compiler which should fix the problem. Try [one of these builds](https://github.com/PixelVision8/PixelVision8/releases) and if it doesn't work I'll open up a more specific ticket to address this.
