### ISSUE TITLE
Is it normal that when app is open the icon changes to some red thing?

### ISSUE THREAD

**Issue by Andrupka** [PixelVision8/PixelVision8#448]
**What is your question?**
Why when I run the app it’s icon changes to some red thing? Is it normal?

**Where did you look before asking here?**
I googled but no results

**Additional Context**
I am using iMac 2019, macOS 11.1

**Comment by jessefreeman** [comment]
Can you please add a screenshot?

**Comment by ilaylevy** [comment]
its normal
its the Monogame logo, the framework used to make PixelVision

**Comment by Andrupka** [comment]
Thanks! already figured it out, it is indeed monogame logo
