### ISSUE TITLE
C# guide is broken

### ISSUE THREAD

**Issue by neilo40** [PixelVision8/PixelVision8#449]
https://github.com/PixelVision8/PixelVision8/wiki/C%23-games which describes how to write C# games refers to files in the repo that don't exist

Specifically, it says to open MonoGameRunner.sln in visual studio.  This file does not exist.

**Comment by Kravitzy** [comment]
same problem here. i cloned the repo but there are no solutions to run

**Comment by Kravitzy** [comment]
You need to open the  PixelVision8.CoreDesktop.csproj file in visual studio
