### ISSUE TITLE
For loops don't run properly?

### ISSUE THREAD

**Issue by gnevesdev** [PixelVision8/PixelVision8#460]
I am not sure if this is a bug, could be some kind of feature, but the for loops for me are not running properly.
I've made these two for loops to draw my procedural map:
```lua
for xx = 0, screen.width, 1 do
  for yy = 0, screen.height, 1 do

  end
end
```
They don't run completely. When I start the game, the map is not fully drawn, and there's no player.

**Comment by jessefreeman** [comment]
Have you tried doing:

```
for x = 1, screen.width do
  for y = 1, screen.height do

  end
end
```

I know for a fact loops are working because all of the tools are using them. Also Lua arrays and loops for the most part are one based so you may be running into an error there?

**Comment by gnevesdev** [comment]
> Have you tried doing:
> 
> ```
> for x = 1, screen.width do
>   for y = 1, screen.height do
> 
>   end
> end
> ```
> 
> I know for a fact loops are working because all of the tools are using them. Also Lua arrays and loops for the most part are one based so you may be running into an error there?

Nope, still not working
![Screenshot from 2021-04-10 19-14-34](https://user-images.githubusercontent.com/49785722/114280432-0f8e6f80-9a31-11eb-9f71-b3874beb27a9.png)

**Comment by jessefreeman** [comment]
can you share the complete code?

**Comment by gnevesdev** [comment]
> can you share the complete code?

Of course:
```lua
local tile_size = 8

local screen_dimension = {}
screen_dimension.width = 21 * tile_size
screen_dimension.height = 19 * tile_size

local player = {}
player.x = 0
player.y = 0
player.flipped = false

function Init()
  BackgroundColor(0)
end

function Update(timeDelta)
  if Button(Buttons.Right) then
    player.x += 1
    player.flipped = false
  end
  
  if Button(Buttons.Left) then
    player.x -= 1
    player.flipped = true
  end
  
  if Button(Buttons.Down) then player.y += 1 end
  
  if Button(Buttons.Up) then player.y -= 1 end
end

function Draw()
  draw_map()
  DrawSprite(0, player.x, player.y, player.flipped)
  RedrawDisplay()
end

function draw_map()
  for xx = 1, screen_dimension.width / tile_size do
    for yy = 1, screen_dimension.height / tile_size do
      DrawSprite(1, xx * tile_size, yy * tile_size)
    end
  end
end
```

**Comment by jessefreeman** [comment]
I see the issue. First you should call RedrawDisplay() first in the Draw() function. Next, you must be running out of sprites since you are calling DrawSprite() in a large loop. If you want to draw the tilemap manually, you can try calling draw_map() in Init and set DrawMode to Tile or TilemapCache.

`DrawSprite(1, xx * tile_size, yy * tile_size, false, false, DrawMode.Tile)`

Hope that helps.
