### ISSUE TITLE
How to compile on Raspberry Pi? (ARM64 Ubuntu 20.10)

### ISSUE THREAD

**Issue by CMDR-Piboy314** [PixelVision8/PixelVision8#461]
**How to compile on Raspberry Pi? (ARM64 Ubuntu 20.10)**
I can't seem to find any build instructions 😕. Does anybody know how to build this?

**I did the ol' Readme.md check but I didn't seem to find any instructions on how to build this**

**Thank you in advance 😄**
Really excited to try PixelVision 8 out, one of the few things that actually **is a game engine** _not_ a framework

**Comment by jessefreeman** [comment]
I haven't had a chance to test the new builds on Pi. Technically you can check out the code and use the .net CLI to compile it. The 1.0.0-features branch is probably the best candidate. If you have .net 5 installed and NPM you can just use the gulp file at the root of that branch's project to kick off the build process.

Once I get the next version out I will turn my attention to doing a proper Pi build.
