### ISSUE TITLE
What file do I run and how?

### ISSUE THREAD

**Issue by ghost** [PixelVision8/PixelVision8#462]
**What file do I run and how?**
I am running Ubuntu 20.10 64bit on a Raspberry Pi 4B if that matters. I have downloaded the linux build.

I see a file called "Pixel Vision 8 in the folder but I tried (In the directory it was downloaded to) "`sudo chmod +x 'Pixel Vision 8'`" and "`./'Pixel Vision 8'`" but then I got an error: "`bash: ./Pixel Vision 8: cannot execute binary file: Exec format error`"

Thank you in advance. Any help would be appreciated 😄 

EDIT: Added Formatting and Error message

**Comment by CMDR-Piboy314** [comment]
Sorry, my account was deleted because I am underage to use this site.
