### ISSUE TITLE
Scale doesn't work (v. 1.0.0)

### ISSUE THREAD

**Issue by TheTolexDok** [PixelVision8/PixelVision8#464]
**Describe the bug**
Basically title. You can change the number in the settings, but it doesn't do anything. Pressing keys like `enter` does nothing. If you close the settings and open them again you will see, that it doesn't even saved, it returned back to 1.
I also tried to change the scale in `bios.json`, but it doesn't care (and still displays 1 in settings)

**To reproduce**
1. go to `settings` from a menu
2. (uncheck `full` if checked to disable full screen) and change `scale` from 1 to (for example) `2`
3. press `quit` (`save` button is not available, and pv8 should auto save this settings, just like with mapping buttons)
4. go back in `settings` and see, that `scale` is back to `1`, and obviously, the size of the window isn't changed

**Note**
You can even type not a number in "scale" in `bios.json` and it will work perfectly (so it is probably not fully developed feature).
here I launched pv8 after this change in bios and it still runs fine:
![here I launched pv8 after this change in bios and it still runs fine](https://user-images.githubusercontent.com/50412868/117273708-93981380-ae86-11eb-9039-43cf1d151214.png)

**Comment by jessefreeman** [comment]
If your monitors don't support the resolution, the scale will be ignored. So based on that screenshot, you wouldn't be able to 2x the default resolution of 512x480.
