### ISSUE TITLE
Feature Request: Simple 2D Physics Engine

### ISSUE THREAD

**Issue by Pranav-Badrinathan** [PixelVision8/PixelVision8#468]
Playing around with this project, I had a hard time implementing proper collision, and I would love to see collision between dynamic objects as well.

What I think would make this process much easier is a simple physics engine as a library. It does not need to be fully feature rich, but simple things such as collisions would be very much appreciated. I've found one that seems nice, though it's in c++: [box2d by erincatto](https://github.com/erincatto/box2d)

An alternative would be implementing at least a collision detection and resolution library? You could go with AABB which is relatively easy, or something more sophisticated like the one shown in this [YouTube video](https://youtu.be/8JJ-4JgR7Dg)

I was also going to get on this case and make a simple prototype implementation, but I'm pretty new to Lua, so it could take long. Can libs be written in c#? I am definitely more comfortable in it. Anyways, please do consider my feature request, as I feel this would make this tool a lot better and easier to use for people who are new to game creation or just want to make something quickly.

**Comment by Pranav-Badrinathan** [comment]
PS: still have not been able to implement collision. The post makes it seem like I know how to, but I can only detect collisions with AABB, not resolve them.

**Comment by jessefreeman** [comment]
Closing this out but if you'd like to see an example of a PV8 game with a physic engine, take a look at this (Space Station 8)[https://github.com/PixelVision8/SpaceStation8]
