### ISSUE TITLE
Wiki doesn't explain what "Pro Tools" are

### ISSUE THREAD

**Issue by henrebotha** [PixelVision8/PixelVision8#515]
The wiki consistently mentions "the Pro Tools", but as far as I can tell doesn't actually explain what that even means.

**Comment by PixelMinecrft** [comment]
This isn't a bug with Pixel Vision 8, the Pro Tools are now part of PV8 and allow you to use the different tools such as music and sprites etc.

**Comment by henrebotha** [comment]
It's a bug in the documentation of PV8.

**Comment by PixelMinecrft** [comment]
There's this thing called the "documentation" label...

**Comment by henrebotha** [comment]
This repository's issues settings are configured such that non-maintainers can't choose labels, and must choose from a predefined list of "bug", "feature request", and "question". I chose the one that most closely matches the nature of the problem. Like I said: A failure of documentation to explain a key concept is a bug in the documentation. But if you have rights to change labels, by all means, change it for me.
