### ISSUE TITLE
v1.1.0 Windows executable crashes.

### ISSUE THREAD

**Issue by heyjustinkim** [PixelVision8/PixelVision8#517]
**Describe the bug**
When I try to run the v1.1.0 executable on Windows, it crashes before loading the PV8 GUI. The attached screenshot is the last thing I see before it crashes.

**To reproduce**
1. Run PV8 v1.1.0 Windows executable.

**Expected behavior**
The program should load and allow me to access the GUI.

**Screenshots**
![image](https://user-images.githubusercontent.com/86444218/141380271-72596502-9537-4cdd-a29f-f8600dde38c6.png)

**Additional notes**
Just wanted to give a heads up about this issue.

**Comment by jessefreeman** [comment]
Thanks, looks like there is an issue with the build script. Looking into how to fix this.

**Comment by jessefreeman** [comment]
There is a new 1.2 build that should fix this. I'll close out the ticket once I get the builds optimized. Right now I am dumping all of the .net files into the folder to make sure it loads correctly.
