### ISSUE TITLE
1.1.0 increment release Linux Exec format error

### ISSUE THREAD

**Issue by silverhikari** [PixelVision8/PixelVision8#518]
**Describe the bug**
when running the 1.1.0 incremental release  version on manjaro, when i try to launch the game i get a "cannot execute binary file: Exec format error"
**To reproduce**
1. overwrite 1.0.0 files with 1.1.0 files
2. launch game using executable
3. nothing appears with error in terminal

**Expected behavior**
the program/game should just continue starting

**Additional notes**
as stated above i am running this on manjaro which is arch based, though i do not know if this a overall linux bug

**Comment by jessefreeman** [comment]
You should try the new 1.2 build I just released and delete your old bios and workspace when booting up for the first time. I'll look into making it easier to upgrade without that crashing.

**Comment by silverhikari** [comment]
yep the new release seems to have fixed the problem!
