### ISSUE TITLE
(SPANISH)"Could not find an OS to boot"

### ISSUE THREAD

**Issue by eggbanana173** [PixelVision8/PixelVision8#523]
**What is your question?**
Ayuda, PixelVision me dice lo siguiente:
"Could not find an OS to boot. 
Insert a disk or restart in "safe mode" by holding down the Shift key"
¿que hago?

**Where did you look before asking here?**
antes, en la 0.9.5+ si funcionaba pero no se porque ahora no me quiere funcionar en la 1.2.0

**Comment by jessefreeman** [comment]
The OS has been broken out of the latest builds until I can get it working with the V2 APIs.

**Comment by eggbanana173** [comment]
pero como lo inicio
