### ISSUE TITLE
Bits

### ISSUE THREAD

**Issue by ATSxp** [PixelVision8/PixelVision8#531]
Hello, I would like to know if PixelVision8 has a 32bit version?  Because it doesn't want to work on my Windows, I believe it's the bits, but I don't see a 32bit option.

**Comment by ATSxp** [comment]
Hello ?

**Comment by jessefreeman** [comment]
Sorry, thought I had replied. I don't have plans to release a 32bit version due to the fact that I don't have any 32bit computers left to test on. You can compile it from the source code if that is a requirement.
