### ISSUE TITLE
OS

### ISSUE THREAD

**Issue by ATSxp** [PixelVision8/PixelVision8#532]
**What is your question?**
Hi, when I run my PixelVision8 it shows me this message, what can it be?

**Where did you look before asking here?**
nothing =/

**Additional context**
img:
![pixel_error](https://user-images.githubusercontent.com/92697714/159357458-1c9f0c51-f6ae-4fbf-8a21-eba48d637050.png)

**Comment by ATSxp** [comment]
I hope you answer soon, because I'm looking forward to using your engine =)

**Comment by ATSxp** [comment]
.

**Comment by eggbanana173** [comment]
intenta instalarlo en la version 0.9.5

**Comment by ATSxp** [comment]
there is no version 0.9.5

**Comment by eggbanana173** [comment]
intenta con el 0.9.2
