### ISSUE TITLE
C# runner doesn't reset sprite counter 

### ISSUE THREAD

**Issue by Traslogan** [PixelVision8/PixelVision8#57]
The C# Runner doesn't reset the sprite counter, meaning that with any sprite limit outside of zero, game chips run out of sprites inside a matter of a few frames.

Tested with a 2x3 spriteblock draw call, gameboy-preset of 40 sprites runs out within 10 frames due to every draw update adding 6 new sprites to the non-resetting pile.

**Comment by jessefreeman** [comment]
The reset has been moved from the Update loop to the Engine class.
