### ISSUE TITLE
Error when running PixelVision8

### ISSUE THREAD

**Issue by Adi-df** [PixelVision8/PixelVision8#63]
Hello, I tried to run PyxelVision8 with the files gived by the link from itch.io. I tried also with the Itch.io desktop App and i got the same error.
[log.txt](https://github.com/PixelVision8/PixelVision8/files/3746700/log.txt)

**Comment by jessefreeman** [comment]
If you are running on Linux you'll need to do the following:

"You need to set your TERM environmental variable to xterm as a fix:

export TERM=xterm"

from this here - https://stackoverflow.com/questions/49242075/mono-bug-magic-number-is-wrong-542

**Comment by Adi-df** [comment]
Thanks you very much.
